package com.personal.jarvis

object CommandCatalog {
    data class Entry(
        val category: String,
        val title: String,
        val commandId: String,
        val phrases: List<String>,
        val summary: String,
        val detail: String,
        val requirements: List<String>,
        val keepsCommandWindowOpen: Boolean,
        val fastPartial: Boolean,
    )

    val entries: List<Entry> = listOf(
        Entry(
            category = "카메라",
            title = "카메라 실행",
            commandId = CommandBus.COMMAND_OPEN_CAMERA,
            phrases = listOf("자비스 카메라 실행", "자비스 카메라 열어", "자비스 카메라 켜"),
            summary = "기본 카메라 앱을 실행합니다.",
            detail = "Android 카메라 인텐트로 기본 카메라 앱을 엽니다. 카메라 세션 명령이므로 처리 후에도 30초 명령 대기를 다시 엽니다.",
            requirements = listOf("기본 카메라 앱 설치", "마이크 권한", "소유자 목소리 등록"),
            keepsCommandWindowOpen = true,
            fastPartial = true,
        ),
        Entry(
            category = "카메라",
            title = "카메라 전면",
            commandId = CommandBus.COMMAND_OPEN_FRONT_CAMERA,
            phrases = listOf("자비스 카메라 전면", "자비스 전면", "자비스 셀피", "자비스 셀카"),
            summary = "기본 카메라를 전면/셀피 모드로 맞춥니다.",
            detail = "전면 카메라 힌트를 넣어 카메라를 열고, Xiaomi 카메라의 전후면 전환 버튼 상태를 읽어 목표가 전면이 아니면 한 번 전환합니다.",
            requirements = listOf("Jarvis 접근성 서비스", "기본 카메라 앱", "마이크 권한", "소유자 목소리 등록"),
            keepsCommandWindowOpen = true,
            fastPartial = true,
        ),
        Entry(
            category = "카메라",
            title = "카메라 후면",
            commandId = CommandBus.COMMAND_OPEN_REAR_CAMERA,
            phrases = listOf("자비스 카메라 후면", "자비스 후면", "자비스 후방", "자비스 뒷카메라"),
            summary = "기본 카메라를 후면 모드로 맞춥니다.",
            detail = "후면 카메라 힌트를 넣어 카메라를 열고, Xiaomi 카메라의 전후면 전환 버튼 상태를 읽어 목표가 후면이 아니면 한 번 전환합니다.",
            requirements = listOf("Jarvis 접근성 서비스", "기본 카메라 앱", "마이크 권한", "소유자 목소리 등록"),
            keepsCommandWindowOpen = true,
            fastPartial = true,
        ),
        Entry(
            category = "카메라",
            title = "카메라 실행 후 촬영",
            commandId = CommandBus.COMMAND_OPEN_CAMERA_AND_TAKE_PHOTO,
            phrases = listOf("자비스 카메라 실행하고 찍어", "자비스 카메라 켜고 사진 찍어"),
            summary = "카메라를 연 뒤 셔터를 누릅니다.",
            detail = "기본 카메라 앱을 실행하고 약 1.5초 뒤 셔터 명령을 보냅니다. 카메라 앱 로딩이 느리면 첫 촬영이 실패할 수 있습니다.",
            requirements = listOf("Jarvis 접근성 서비스", "기본 카메라 앱", "마이크 권한", "소유자 목소리 등록"),
            keepsCommandWindowOpen = true,
            fastPartial = true,
        ),
        Entry(
            category = "카메라",
            title = "사진 찍기",
            commandId = CommandBus.COMMAND_TAKE_PHOTO,
            phrases = listOf(
                "자비스 사진 찍어",
                "자비스 사진 찍어줘",
                "자비스 찍어",
                "자비스 셔터",
                "자비스 셔터 눌러",
                "자비스 촬영해줘",
                "자비스 찰칵",
            ),
            summary = "현재 카메라 화면에서 셔터를 누릅니다.",
            detail = "실행 속도를 위해 Xiaomi 카메라의 화면 비율 기반 셔터 좌표를 먼저 탭하고, 제스처 dispatch가 실패한 경우 접근성 노드에서 셔터 버튼을 찾습니다. 카메라 앱이 이미 열려 있을 때 가장 안정적입니다.",
            requirements = listOf("Jarvis 접근성 서비스", "카메라 앱이 전면에 있거나 바로 열릴 수 있는 상태", "마이크 권한", "소유자 목소리 등록"),
            keepsCommandWindowOpen = true,
            fastPartial = true,
        ),
        Entry(
            category = "카메라",
            title = "카메라 필터",
            commandId = CommandBus.COMMAND_OPEN_FILTERS,
            phrases = listOf("자비스 카메라 필터", "자비스 필터", "자비스 효과", "자비스 색감"),
            summary = "카메라 필터/효과 버튼을 엽니다.",
            detail = "Xiaomi 카메라 화면에서 필터, 효과, Leica, 색감 관련 접근성 노드를 찾고, 실패하면 필터 영역으로 예상되는 좌표를 탭합니다.",
            requirements = listOf("Jarvis 접근성 서비스", "카메라 앱 화면", "마이크 권한", "소유자 목소리 등록"),
            keepsCommandWindowOpen = true,
            fastPartial = true,
        ),
        Entry(
            category = "카메라",
            title = "카메라 전환",
            commandId = CommandBus.COMMAND_SWITCH_CAMERA,
            phrases = listOf("자비스 카메라 전환", "자비스 전후면 전환", "자비스 렌즈 전환"),
            summary = "현재 카메라의 전면/후면을 토글합니다.",
            detail = "Xiaomi 카메라의 전후면 전환 버튼을 찾아 탭합니다. 현재 렌즈 상태는 가능한 경우 접근성 노드 설명에서 갱신합니다.",
            requirements = listOf("Jarvis 접근성 서비스", "카메라 앱 화면", "마이크 권한", "소유자 목소리 등록"),
            keepsCommandWindowOpen = true,
            fastPartial = true,
        ),
        Entry(
            category = "앱 이동",
            title = "카메라 종료",
            commandId = CommandBus.COMMAND_HOME,
            phrases = listOf("자비스 카메라 종료", "자비스 카메라 닫아", "자비스 카메라 꺼", "자비스 종료", "자비스 홈"),
            summary = "홈으로 이동해 현재 앱을 빠져나옵니다.",
            detail = "카메라 앱을 강제 종료하지 않고 Android 접근성 전역 홈 액션을 실행합니다. 카메라 세션 명령으로 취급되어 다음 명령을 받을 수 있게 30초 명령 대기를 다시 엽니다.",
            requirements = listOf("Jarvis 접근성 서비스", "마이크 권한", "소유자 목소리 등록"),
            keepsCommandWindowOpen = true,
            fastPartial = true,
        ),
        Entry(
            category = "앱 이동",
            title = "뒤로",
            commandId = CommandBus.COMMAND_BACK,
            phrases = listOf("자비스 뒤로", "자비스 백"),
            summary = "Android 뒤로 가기 동작을 실행합니다.",
            detail = "접근성 전역 뒤로 가기 액션을 실행합니다. 카메라나 설정 화면에서 한 단계 뒤로 이동할 때 사용합니다.",
            requirements = listOf("Jarvis 접근성 서비스", "마이크 권한", "소유자 목소리 등록"),
            keepsCommandWindowOpen = true,
            fastPartial = true,
        ),
        Entry(
            category = "시스템",
            title = "화면 켜기",
            commandId = CommandBus.COMMAND_WAKE_SCREEN,
            phrases = listOf("자비스 화면 켜", "자비스 디스플레이 켜줘", "자비스 폰 깨워"),
            summary = "꺼진 화면을 깨워 잠금화면을 보이게 합니다.",
            detail = "짧은 wake lock으로 디스플레이를 켭니다. Android 보안 정책상 잠금 해제까지 자동으로 수행하지는 않습니다.",
            requirements = listOf("마이크 권한", "소유자 목소리 등록"),
            keepsCommandWindowOpen = false,
            fastPartial = true,
        ),
        Entry(
            category = "시스템",
            title = "화면 끄기",
            commandId = CommandBus.COMMAND_SLEEP_SCREEN,
            phrases = listOf("자비스 화면 꺼", "자비스 디스플레이 꺼줘", "자비스 폰 잠가"),
            summary = "화면을 끄고 기기를 잠급니다.",
            detail = "접근성 전역 잠금화면 액션을 실행합니다. 비밀번호, 지문, 얼굴인식 같은 사용자 인증은 우회하지 않습니다.",
            requirements = listOf("Jarvis 접근성 서비스", "마이크 권한", "소유자 목소리 등록"),
            keepsCommandWindowOpen = false,
            fastPartial = true,
        ),
        Entry(
            category = "Jarvis",
            title = "Jarvis 잠들기",
            commandId = CommandBus.COMMAND_STOP_LISTENING,
            phrases = listOf("자비스 잠들어", "자비스 멈춰", "자비스 중지", "자비스 그만"),
            summary = "현재 명령 대기 창을 닫습니다.",
            detail = "현재 30초 command window를 닫고 하이퍼아일랜드 표시를 숨깁니다. 호출형 정책에서는 명령 대기가 끝나면 음성 foreground service도 내려갑니다.",
            requirements = listOf("마이크 권한", "소유자 목소리 등록"),
            keepsCommandWindowOpen = false,
            fastPartial = true,
        ),
        Entry(
            category = "Jarvis",
            title = "Jarvis 완전 종료",
            commandId = CommandBus.COMMAND_STOP_SERVICE,
            phrases = listOf("자비스 완전 종료", "자비스 서비스 종료", "자비스 앱 종료", "자비스 완전히 꺼"),
            summary = "Jarvis 음성 서비스를 종료합니다.",
            detail = "현재 실행 중인 Jarvis 음성 foreground service를 종료합니다. 앱을 삭제하거나 Android 설정의 강제 종료를 수행하는 것은 아닙니다.",
            requirements = listOf("마이크 권한", "소유자 목소리 등록"),
            keepsCommandWindowOpen = false,
            fastPartial = true,
        ),
    )
}
